# Generated by Django 4.1 on 2022-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, null=True)),
                ("description", models.TextField(max_length=10, null=True)),
                ("priority", models.IntegerField(max_length=30)),
                ("status", models.IntegerField(max_length=30)),
                (
                    "start_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated On"),
                ),
                (
                    "end_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Updated On"),
                ),
            ],
        ),
    ]
