# Generated by Django 4.1 on 2022-08-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_remove_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="task", name="priority", field=models.IntegerField(),
        ),
    ]
